#!/bin/sh
### BEGIN INIT INFO
# Provides:          soracom_dial
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.  This example start a
#                    single forking daemon capable of writing a pid
#                    file.  To get other behavoirs, implemend
#                    do_start(), do_stop() or other functions to
#                    override the defaults in /lib/init/init-d-script.
### END INIT INFO

start(){
	echo -n "connect air...\n"
	do_wvdial &
	return 0
}

stop(){
	echo -n "stopping connect air...\n"

	pid=`ps ax | grep -v grep | grep do_wvdial | awk '{ print $1 }'`
	kill $pid
	killall wvdial

	return 0
}

case $1 in
	start)
		start
		;;
	stop)
		stop
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 2
		;;
esac
