#!/bin/sh
### BEGIN INIT INFO
# Provides:          soracomair
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: soracomair
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.  This example start a
#                    single forking daemon capable of writing a pid
#                    file.  To get other behavoirs, implemend
#                    do_start(), do_stop() or other functions to
#                    override the defaults in /lib/init/init-d-script.
### END INIT INFO

do_start(){
	echo -n "connect air...\n"
	logger "starting soracomair"
	wvdial_soracomair &
	logger "started soracomair"
	return 0
}

do_stop(){
	echo -n "stopping soracomair...\n"
	logger "stopping soracomair"

	pid=`ps ax | grep -v grep | grep wvdial_soracomair | awk '{ print $1 }'`
	kill $pid
	killall wvdial

	logger "stopped soracomair pid=$pid"

	return 0
}

case $1 in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 2
		;;
esac
