#!/bin/bash

print_log() {
	echo "[wvdial_soracomair] $*"
	echo "[wvdial_soracomair] $*"
}

dialup() {
	cat > /etc/wvdial.conf << EOF
[Dialer Defaults]
Init1 = ATH
Init2 = AT&F
Init3 = ATZ
Init4 = ATQ0 V1 E1 S0=0 &C1 &D2
Init5 = AT+CGDCONT=1,"IP","soracom.io"
Dial Attempts = 3
Modem Type = Analog Modem
Dial Command = ATD
Stupid Mode = yes
Baud = 460800
New PPPD = yes
Modem = $1
ISDN = 0
Phone = *99***1#
APN = soracom.io
Username = sora
Password = sora
Carrier Check = no
Auto DNS = 1
Check Def Rpoute = 1
EOF

	print_log "waiting for modem device"
	for i in {1..30}
	do
		[ -e $1 ] && break
		echo -n "."
		sleep 1
	done
	[ $i -eq 30 ] && (print_log "modem not found" ; exit 1 )

	/etc/init.d/ntp stop

	while true
	do
		print_log "executing wvdial"

		wvdial &
		sleep 10

		ip route del default
		ip route add default dev ppp0

		while true
		do
			ifconfig ppp0 > /dev/null 2>&1
			if [ $? -ne 0 ]
			then
				print_log "ppp0 is down, reconnecting after 30sec"
				killall wvdial
				break
			else
				print_log "ppp0 is OK, check again after 60sec"
			fi
			ntpdate 133.243.238.243
			sleep 60
		done
		sleep 30
	done
}

disconnect() {
	killall wvdial_soracomair
	killall wvdial
}

if [ $UID -ne 0 ]
then
	print_log "use root or sudo"
	exit 1;
fi

dialup /dev/ttyUSB2
